#!/usr/bin/env python3

import rospy
import getch
from geometry_msgs.msg import Twist
pub = rospy.Publisher('turtle1/cmd_vel', Twist, queue_size=10)
n = rospy.init_node('turtle_teleoperator',anonymous=True)
rate = rospy.Rate(50)
move_cmd = Twist()
linear_speed = 1.0
angular_speed = 1.0

def initialise():
	while not rospy.is_shutdown():
		k = ord(getch.getch())
		print(k)
		if k==119:
			rospy.loginfo("Up")
			move_turtle(linear_speed, 0.0)
		if k==115:
			rospy.loginfo("Down")
			move_turtle(-linear_speed, 0.0)
		if k==100:
			rospy.loginfo("Right")
			move_turtle(0.0, -angular_speed)
		if k==97:
			rospy.loginfo("Left")
			move_turtle(0.0, angular_speed)
			rospy.loginfo("current speed is %f" % linear_speed)     

def move_turtle(x, z):
    move_cmd.linear.x = x
    move_cmd.angular.z = z
    pub.publish(move_cmd)
    rate.sleep()

if __name__=="__main__":
    initialise()

